(require 'inflect)
(require 'ert)

(ert-deftest inflect-dasherize-test ()
  (should (equal "" (inflect-dasherize "")))
  (should (equal "-" (inflect-dasherize "-")))
  (should (equal "-" (inflect-dasherize "_")))
  (should (equal "client-id" (inflect-dasherize "client_id")))
  (should (equal 'client-id (inflect-dasherize 'client_id)))
  (should (equal :client-id (inflect-dasherize :client_id)))
  (should (equal '(client-id . "client_id") (inflect-dasherize '(client_id . "client_id"))))
  (should (equal (inflect-dasherize '((client_id . "client_id") ("client_secret" "client_secret")))
                 '((client-id . "client_id") ("client-secret" "client_secret"))))
  (let ((hash (make-hash-table)))
    (puthash "client_id" "client-id" hash)
    (puthash 'client_secret "client-secret" hash)
    (puthash :grant_type "grant-type" hash)
    (let ((hash (inflect-dasherize hash)))
      (should (equal 3 (hash-table-count hash)))
      (should (equal "client-id" (gethash "client-id" hash)))
      (should (equal "client-secret" (gethash 'client-secret hash)))
      (should (equal "grant-type" (gethash :grant-type hash))))))

(ert-deftest inflect-underscore-test ()
  (should (equal "" (inflect-underscore "")))
  (should (equal "_" (inflect-underscore "_")))
  (should (equal "_" (inflect-underscore "-")))
  (should (equal "client_id" (inflect-underscore "client-id")))
  (should (equal 'client_id (inflect-underscore 'client-id)))
  (should (equal :client_id (inflect-underscore :client-id)))
  (should (equal '(client_id . "client-id") (inflect-underscore '(client-id . "client-id"))))
  (should (equal (inflect-underscore '((client-id . "client_id") ("client-secret" "client_secret")))
                 '((client_id . "client_id") ("client_secret" "client_secret"))))
  (let ((hash (make-hash-table)))
    (puthash "client-id" "client-id" hash)
    (puthash 'client-secret "client-secret" hash)
    (puthash :grant-type "grant-type" hash)
    (let ((hash (inflect-underscore hash)))
      (should (equal 3 (hash-table-count hash)))
      (should (equal "client-id" (gethash "client_id" hash)))
      (should (equal "client-secret" (gethash 'client_secret hash)))
      (should (equal "grant-type" (gethash :grant_type hash))))))

(ert-deftest inflect-url-encode-test ()
  (should (equal (inflect-url-encode "") ""))
  (should (equal (inflect-url-encode "x") "x"))
  (should (equal (inflect-url-encode "=") "%3D"))
  (should (equal (inflect-url-encode "a 1") "a%201"))
  (should (equal (inflect-url-encode '(a-1 1)) "a-1=1"))
  (should (equal (inflect-url-encode '((a-1 1) (b-2 2))) "a-1=1&b-2=2"))
  (should (equal (inflect-url-encode '((a-1 . 1) (b-2 . 2))) "a-1=1&b-2=2")))

(provide 'inflect-test)
